#!/usr/bin/env python3
"""
Find orphan uncompressed audit log objects left behind by the gzip switchover.

When gzip compression is first enabled, any audit log file that was still being
written at switchover gets re-downloaded in full and uploaded under a NEW key
with a ``.gz`` suffix. The original uncompressed object (same key without
``.gz``) is NOT overwritten, so both objects linger in the same prefix:

    audit-logs/.../server_audit.log      <- pre-switch, partial (orphan)
    audit-logs/.../server_audit.log.gz   <- post-switch, full superset

Athena scans the prefix and counts the overlapping rows TWICE. This does not
self-heal: the orphan stays until removed.

This script is READ-ONLY. It lists every key ``X`` for which ``X.gz`` also
exists (the duplicate pairs), so you can review and delete the orphan ``X``
objects by hand. Use ``--write-script`` to emit a reviewable shell script of
``aws s3api delete-object`` commands — the script deletes nothing itself.

Only objects that have BOTH an uncompressed and a ``.gz`` twin are reported.
A lone uncompressed ``.log`` (historical, pre-deployment) is legitimate and is
left alone; a lone ``.gz`` is the normal steady state.

Usage:
    python find_orphan_uncompressed_logs.py --bucket BUCKET [--prefix audit-logs/]
                                            [--region REGION] [--write-script PATH]

Examples:
    python find_orphan_uncompressed_logs.py --bucket my-audit-logs
    python find_orphan_uncompressed_logs.py --bucket my-audit-logs --region us-west-1
    python find_orphan_uncompressed_logs.py --bucket my-audit-logs --write-script cleanup.sh
"""

import argparse
import shlex
import sys


def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description="List orphan uncompressed audit log objects shadowed by a .gz twin (read-only)."
    )
    parser.add_argument("--bucket", required=True, help="S3 bucket holding audit logs")
    parser.add_argument("--prefix", default="audit-logs/", help="Key prefix to scan (default: audit-logs/)")
    parser.add_argument("--region", default=None, help="AWS region")
    parser.add_argument(
        "--write-script", default=None, metavar="PATH",
        help="Write a reviewable shell script of delete commands to PATH (deletes nothing now)",
    )
    return parser.parse_args(argv)


def create_boto3_session(region=None):
    import boto3
    kwargs = {}
    if region:
        kwargs["region_name"] = region
    return boto3.Session(**kwargs)


def list_objects(s3_client, bucket, prefix):
    """Return {key: size} for every object under prefix."""
    objects = {}
    paginator = s3_client.get_paginator("list_objects_v2")
    for page in paginator.paginate(Bucket=bucket, Prefix=prefix):
        for obj in page.get("Contents", []):
            objects[obj["Key"]] = obj["Size"]
    return objects


def find_orphans(objects):
    """Return orphan pairs: uncompressed keys that also have a .gz twin.

    Each entry: {"orphan": key, "orphan_size": int, "gz": key+".gz",
    "gz_size": int}. The orphan is the uncompressed object to delete.
    """
    orphans = []
    for key, size in objects.items():
        if key.endswith(".gz"):
            continue
        gz_key = key + ".gz"
        if gz_key in objects:
            orphans.append({
                "orphan": key,
                "orphan_size": size,
                "gz": gz_key,
                "gz_size": objects[gz_key],
            })
    orphans.sort(key=lambda o: o["orphan"])
    return orphans


def human_bytes(n):
    value = float(n)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if value < 1024 or unit == "TB":
            return f"{value:.1f}{unit}" if unit != "B" else f"{int(value)}B"
        value /= 1024


def print_summary(orphans, bucket):
    if not orphans:
        print("\nNo orphan uncompressed objects found — nothing to clean up.")
        return
    print(f"\nFound {len(orphans)} orphan uncompressed object(s) shadowed by a .gz twin:\n")
    print(f"  {'ORPHAN (delete this)':<70} {'SIZE':>10}   {'.GZ TWIN SIZE':>13}")
    print(f"  {'-'*70} {'-'*10}   {'-'*13}")
    total = 0
    for o in orphans:
        total += o["orphan_size"]
        print(f"  {o['orphan']:<70} {human_bytes(o['orphan_size']):>10}   {human_bytes(o['gz_size']):>13}")
    print(f"\n  Reclaimable (orphan bytes): {human_bytes(total)} across {len(orphans)} object(s)")
    print(f"  Bucket: {bucket}")
    print("\n  These uncompressed objects overlap their .gz twins and cause Athena")
    print("  to double-count rows. Review, then delete the ORPHAN keys above.")


def write_cleanup_script(orphans, bucket, region, path):
    lines = [
        "#!/usr/bin/env bash",
        "# Auto-generated by find_orphan_uncompressed_logs.py — REVIEW BEFORE RUNNING.",
        "# Deletes orphan uncompressed audit log objects shadowed by a .gz twin.",
        "# Each object's .gz twin contains a superset of its data; deleting the",
        "# uncompressed object removes Athena double-counting without data loss.",
        "set -euo pipefail",
        "",
    ]
    region_arg = f" --region {shlex.quote(region)}" if region else ""
    for o in orphans:
        lines.append(
            f"aws s3api delete-object --bucket {shlex.quote(bucket)} "
            f"--key {shlex.quote(o['orphan'])}{region_arg}"
        )
    lines.append("")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"\nWrote {len(orphans)} delete command(s) to {path}")
    print(f"Review it, then run:  bash {path}")


def main(argv=None):
    args = parse_args(argv)
    try:
        session = create_boto3_session(args.region)
    except Exception as exc:
        print(f"ERROR: Failed to create AWS session: {exc}", file=sys.stderr)
        sys.exit(1)

    s3_client = session.client("s3")
    print(f"Scanning s3://{args.bucket}/{args.prefix} ...")
    try:
        objects = list_objects(s3_client, args.bucket, args.prefix)
    except Exception as exc:
        print(f"ERROR: Failed to list objects: {exc}", file=sys.stderr)
        sys.exit(1)

    print(f"Listed {len(objects)} object(s).")
    orphans = find_orphans(objects)
    print_summary(orphans, args.bucket)

    if orphans and args.write_script:
        try:
            write_cleanup_script(orphans, args.bucket, args.region, args.write_script)
        except Exception as exc:
            print(f"ERROR: Failed to write cleanup script: {exc}", file=sys.stderr)
            sys.exit(1)


if __name__ == "__main__":
    main()
